### ISSUE TITLE
Dúvida sobre a contabilização de trocas do quicksort

### ISSUE THREAD

**Issue by pkr404** [PatrickRudgeri/trabalho_ed2#2]
@larissalimaa:
![image](https://user-images.githubusercontent.com/20716307/96655328-929cfb80-1313-11eb-9a69-74a8af45f5fd.png)
![image](https://user-images.githubusercontent.com/20716307/96655358-a8122580-1313-11eb-9903-754c93ed1d52.png)

**Comment by pkr404** [comment]
Em minha opinião uma troca é contabilizada da seguinte forma:
Para servir de exemplo, criei uma função pra fazer uma troca entre duas variáveis inteiras. O contador de trocas só é incrementado 1 vez quando essa função é chamada. (`a` foi **trocado** com `b` apenas 1 vez ). 
Seriam 3 atribuições, mas 1 troca apenas.
![image](https://user-images.githubusercontent.com/20716307/96655630-5918c000-1314-11eb-9850-f531f0adf96d.png)

**Comment by larissalimaa** [comment]
então, vai depender do que exatamente o professor quer. Se ele quer que contabilize as movimentações de dados (salva título em uma variavél auxiliar e troca esquerda com a direita) ou contabilizar troca das posições dos título.  Se for este último caso, concordo com você que seja somente 1 troca mesmo. A luci tinha comentado que seria só uma também

**Comment by pkr404** [comment]
O Caniato disse para nós considerarmos o exemplo acima como 3 trocas (movimentações de dados).
